### ISSUE TITLE
dockerComposeTest does not remove Docker instances when the compliation fails

### ISSUE THREAD

**Issue by laurin-no** [Tapad/sbt-docker-compose#107]
In the last days I noticed that the plugin sets up a local Docker instance when calling `dockerComposeTest` but it does not get stopped and removed when the compliation fails. It looks like `docker-compose down` is not called in this case.

I am running version `1.0.30` of the plugin with `sbt 1.0.3` on Ubuntu 16.04 but the Macbook of my colleague shows the same behaviour.

Is this a bug or a feature?

**Comment by kurtkopchik** [comment]
Hi @laurin-no - Could you include the console output from `dockerCompseTest` in the issue so I can get a better picture of what you are seeing?

Also, if would be great if you can try it using the latest version:
`addSbtPlugin("com.tapad" % "sbt-docker-compose" % "1.0.32")`

**Comment by laurin-no** [comment]
I updated it to the latest version and tried it again with this output:

```[IJ]sbt:integration> dockerComposeTest
Starting Test Pass against a new local Docker Compose instance.
Creating Local Docker Compose Environment.
Reading Compose File: /home/laurin/integration/docker-compose.yml
Created Compose File with Processed Custom Tags: /tmp/compose-updated631794463781346840.yml
Pulling Docker images except for locally built images and images defined as <skipPull> or <localBuild>.
9.4.10: Pulling from library/postgres
Digest: sha256:0dfca35b7cc89b3faf1a4d2df34aa59ede4f5eeceaecbb82e165d686324f230d
Status: Image is up to date for postgres:9.4.10
Creating network "51931_default" with the default driver
Creating 51931_db_1 ... 
Creating 51931_db_1
Waiting for container Id to be available for service 'db' time remaining: 499
db Container Id: 9993399f27db
Inspecting container 9993399f27db to get the port mappings
WARNING: No swap limit support
Non-OSX environment detected. Using the host from the container.

The following endpoints are available for your local instance: 51931
+---------+------------------+-------------+--------------+----------------+--------------+---------+
| Service | Host:Port        | Tag Version | Image Source | Container Port | Container Id | IsDebug |
+=========+==================+=============+==============+================+==============+=========+
| db      | 172.20.0.1:32771 | 9.4.10      | defined      | 5432           | 9993399f27db |         |
+---------+------------------+-------------+--------------+----------------+--------------+---------+
Instance commands:
1) To stop instance from sbt run:
   dockerComposeStop 51931
2) To open a command shell from bash run:
   docker exec -it <Container Id> bash
3) To view log files from bash run:
   docker-compose -p 51931 -f /tmp/compose-updated631794463781346840.yml logs -f
4) To execute test cases against instance from sbt run:
   dockerComposeTest 51931
[info] Compiling and Packaging test cases using testCasesPackageTask ...
[info] Compiling 1 Scala source to /home/laurin/integration/target/scala-2.12/classes ...
[error] /home/laurin/integration/src/main/scala/bla/common/client/BlaClient.scala:62:3: not found: value asd
[error]   asd
[error]   ^
[error] one error found
[error] (compile:compileIncremental) Compilation failed
```
Here is also the output of `docker ps`:

```   
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                     NAMES
9993399f27db        postgres:9.4.10     "/docker-entrypoint.…"   7 minutes ago       Up 7 minutes        0.0.0.0:32771->5432/tcp   51931_db_1
``` 
The remaining network bridges cause me problems with my network connection and I have to manually clean it up every few days.

**Comment by kurtkopchik** [comment]
Hi @laurin-no - Thanks for sending the additional information. I agree, that it would be preferred to have the newly launched docker container cleaned up in the case that the test code compilation fails during the execution of the `dockerComposeTest` command.

I've made an [update](https://github.com/Tapad/sbt-docker-compose/pull/106) to fix this issue and published an updated version of `1.0.33-SNAPSHOT` with the change:

```
resolvers += "Sonatype Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots/"
addSbtPlugin("com.tapad" % "sbt-docker-compose" % "1.0.33-SNAPSHOT")
```
Please try it out and let me know if it addresses your issue. If so, I'll include it in the next official release. Thanks again for reporting the issue.

**Comment by kurtkopchik** [comment]
Hi @laurin-no - Just checking in to see if you had a chance to try out the update?

**Comment by laurin-no** [comment]
@kurtkopchik I'm sorry, I will take a look tomorrow.

**Comment by laurin-no** [comment]
@kurtkopchik I tried the update and it now works as expected. Thank you very much.

**Comment by kurtkopchik** [comment]
Hi @laurin-no - Thanks for validating the changes. I've published an official release with the update:

`addSbtPlugin("com.tapad" % "sbt-docker-compose" % "1.0.33")`
