### ISSUE TITLE
multi project build with sbt-native-packager

### ISSUE THREAD

**Issue by maocorte** [Tapad/sbt-docker-compose#109]
Hi,
I'm trying to develop a multi project using sbt-native-packager but i can't find the way to define `dockerImageCreationTask` on root project in the right way.

Below an extract of mine `build.sbt`:

```
lazy val root = project
  .in(file("."))
  ...
  .settings(
    ...
    dockerImageCreationTask := ???,
    variablesForSubstitution := (variablesForSubstitution in prj1).value ++
      (variablesForSubstitution in prj2).value
  )
  .aggregate(prj1, prj2)

lazy val prj1 = project
 .settings(
    ...
    dockerImageCreationTask := (publishLocal in Docker).value,
    variablesForSubstitution := Map(
      "prj1_image_name" -> s"${dockerRepository.value.get}/${name.value}:${version.value}"
    )
  )

lazy val prj2 = project
 .settings(
    ...
    dockerImageCreationTask := (publishLocal in Docker).value,
    variablesForSubstitution := Map(
      "prj2_image_name" -> s"${dockerRepository.value.get}/${name.value}:${version.value}"
    )
  )
```

If I set `dockerImageCreationTask := (dockerImageCreationTask in prj1).value` in the root project it works for the `prj1` but i can't find a way to concatenate ` (dockerImageCreationTask in prj1).value` and `(dockerImageCreationTask in prj2).value`.
Is there a way to solve this problem?

Thank you for the help!!

**Comment by maocorte** [comment]
ok, found the solution:

```
dockerImageCreationTask := {
  (dockerImageCreationTask in prj1).value
  (dockerImageCreationTask in prj2).value
}
```

Hope could be helpful for other users. Cheers

**Comment by kurtkopchik** [comment]
Hi @maocorte - I'm glad you were able to figure it out and thanks for using the plugin!
