### ISSUE TITLE
Forthcoming Deprecation / Transfer of Ownership Notice

### ISSUE THREAD

**Issue by jeffreyolchovy** [Tapad/sbt-docker-compose#120]
Given that this plugin is (1) no longer widely (if at all) leveraged at Tapad, and (2) that the original author is no longer employed by us, we have determined that the Tapad team will no longer invest time and effort in the further maintenance and development of sbt-docker-compose.

We did (and do not) intend to implicitly abandon this project. As such, we would like to transition to a more explicit strategy for deprecating this plugin, or our role in the development of this plugin.

Options we are considering are as follows:
- Deprecate and encourage the use of a different project (which solves the same problem and is still under active development/maintenance)
- Encourage a community member to fork the project and take over maintenance going forward.

If you are a community member that feels one way or another, please share your thoughts and suggestions below.

I intend to make a decision (considering this community input), by no later than November 17, 2019.

Until our new policy is announced, I personally will be available to merge PRs and release new versions of this plugin on an as needed or requested basis.

**Comment by edwardcapriolo** [comment]
I can host it at I have a sontype account and can release changes to maven central

**Comment by jeffreyolchovy** [comment]
Thanks for the offer @edwardcapriolo, but that will not be necessary as @kurtkopchik (original author and maintainer) will be taking over the custodianship of this plugin via his fork @ https://github.com/shaked0wn/sbt-docker-compose.

Expect a formal hand-over and deprecation / transfer of ownership notice to appear in this project's README.

Thanks all.
