### ISSUE TITLE
dockerComposeTest fails if the classpath has a space in it

### ISSUE THREAD

**Issue by tobym** [Tapad/sbt-docker-compose#13]
Observe a same test command below, where the project lives in `/path/to/some directory with spaces/myproject`.  This is passed verbatim to java, so the command will fail.  Wrapping in quotes should do the trick (have not tested yet).

```
java  -Dredis:6379=172.17.0.1:32787 -Dredis:containerId=447d3ea0ab57 -cp /path/to/some directory with spaces/myproject/target/scala-2.11/classes:/home/myuser/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.7.jar ...
```

**Comment by kurtkopchik** [comment]
Nice find. If you get a chance to test it out let me know. Otherwise, I will try it out myself and include the fix in the next release.

**Comment by kurtkopchik** [comment]
The fix ended up being a bit more complicated than just adding the quotes. I just merged a [change](https://github.com/Tapad/sbt-docker-compose/commit/cc8cfbd71262313f0c9ed181cb9479947a53bb15) from @edward720 with the fix.

I'll close this issue out after the next release. Thanks again for reporting the bug!

**Comment by kurtkopchik** [comment]
Closing this issue out as 1.0.9 has been released:
`addSbtPlugin("com.tapad" % "sbt-docker-compose" % "1.0.9")`
