### ISSUE TITLE
sbt dockerComposeTest returns exit code 0 if test run aborts

### ISSUE THREAD

**Issue by rdgreen** [Tapad/sbt-docker-compose#23]
It should return a non-0 exit code, otherwise a CI server will think that the test completed successfully.

Workaround (on Mac/Linux):

```
sbt dockerComposeUp && sbt test && sbt dockerComposeStop
```

**Comment by kurtkopchik** [comment]
Version 1.0.13 has been released with a fix for this issue:
`addSbtPlugin("com.tapad" % "sbt-docker-compose" % "1.0.13")`

Thanks again @shanethehat!

**Comment by shanethehat** [comment]
Awesome, thanks for the quick release!
