### ISSUE TITLE
dockerComposeTest doesn't create test-reports

### ISSUE THREAD

**Issue by dpfeiffer** [Tapad/sbt-docker-compose#33]
Unfortunately I recognised that sbt-docker-compose dockerComposeTest does not create test reports even if I can see that all tests are run. 

Is there a way to force the generation of test-reports?

**Comment by kurtkopchik** [comment]
Hi @dpfeiffer, the current version of the plugin does not have a way to force the generation of test reports. However, I think that this is a great suggestion so I created an initial snapshot release that adds support for this. It's not fully tested yet but please try it out and let me know if it satisfies what you are looking for.

```
resolvers += "Sonatype Snaopshots" at "https://oss.sonatype.org/content/repositories/snapshots/"
addSbtPlugin("com.tapad" % "sbt-docker-compose" % "1.0.15-SNAPSHOT")
```
You can now provide [ScalaTest reporting](http://www.scalatest.org/user_guide/using_the_runner) arguments to the new `settingKey`
`testExecutionArgs` to specify the reporting options that you want to use.

For example, in build.sbt you can now define the following to have html reports created:
`testExecutionArgs := "-h target/htmldir"`

However, I also had to include`"org.pegdown" % "pegdown" % "1.6.0" % "test"` in my `libraryDependencies` for the html reporting to work.

Check out the `basic-with-tests` project in the branch `feature/testPassArgs` for a working example of how to use it:
https://github.com/Tapad/sbt-docker-compose/blob/feature/testPassArgs/examples/basic-with-tests/build.sbt

If this works for you I can get it integrated into the next official release. Thanks again for the feedback!

**Comment by dpfeiffer** [comment]
Hi @kurtkopchik, thanks for that amazingly fast reply. I will try it out and give  feedback how it works. I gave it a short try and it looks good. I will keep you updated.

**Comment by dpfeiffer** [comment]
@kurtkopchik looks good and seems to work as expected

**Comment by kurtkopchik** [comment]
Hi @dpfeiffer, I published an official release which contains support for test pass report generation.

`addSbtPlugin("com.tapad" % "sbt-docker-compose" % "1.0.15")`

Thanks again for the feedback and for using the plugin!
