### ISSUE TITLE
dockerComposeTest doesn't pick up test resources

### ISSUE THREAD

**Issue by dpfeiffer** [Tapad/sbt-docker-compose#36]
I have a play application and resources in the test/resources folder which is the default test-resources folder for a play application. If I run a test which accesses test resources from `dockerComposeTest` the test resources are not on the classpath although they are if I run the same test witch `test`.

**Comment by kurtkopchik** [comment]
Hi @dpfeiffer, the class path for test dependencies is defined in the plugin as an overridable `taskKey` named `testDependenciesClasspath`.

`testDependenciesClasspath =: // The path to all managed and unmanaged Test and Compile dependencies. This path needs to include the ScalaTest Jar for the tests to execute. This defaults to all managedClasspath and unmanagedClasspath in the Test and fullClasspath in the Compile Scope.`

Here is the default implementation:
```
testDependenciesClasspath := {
  val fullClasspathCompile = (fullClasspath in Compile).value
  val classpathTestManaged = (managedClasspath in Test).value
  val classpathTestUnmanaged = (unmanagedClasspath in Test).value
  (fullClasspathCompile.files ++ classpathTestManaged.files ++   classpathTestUnmanaged.files).map(_.getAbsoluteFile).mkString(":")
}
```

Is there an additional sbt setting/path that you can append to the default list allow your test resources to be located from your Play application tests? Depending on what the solution is it's possible that the default set of paths I'm building needs to be updated to account for your scenario.

**Comment by kurtkopchik** [comment]
@dpfeiffer Maybe something like the following:
```
    testDependenciesClasspath := {
      val fullClasspathCompile = (fullClasspath in Compile).value
      val classpathTestManaged = (managedClasspath in Test).value
      val classpathTestUnmanaged = (unmanagedClasspath in Test).value
      val testResources = (resources in Test).value
      (fullClasspathCompile.files ++ classpathTestManaged.files ++ classpathTestUnmanaged.files ++ testResources).map(_.getAbsoluteFile).mkString(":")
    }
```

**Comment by dpfeiffer** [comment]
@kurtkopchik Thank you for your fast reply, it works as expected when I set the testDependenciesClasspath manually (like you suggested). I should have read the docs more carefully. I think that adding the testResources as a default would suite most scenarios as I assume it's a default behaviour (having access to test resources) for running test.

**Comment by kurtkopchik** [comment]
Thanks @dpfeiffer! I'm glad that worked for you.

I've published a release that now includes the test resources in the classpath by default when executing `dockerComposeTest`.

`addSbtPlugin("com.tapad" % "sbt-docker-compose" % "1.0.16")`
