### ISSUE TITLE
Support IntegrationTest scope

### ISSUE THREAD

**Issue by Cosmo439** [Tapad/sbt-docker-compose#38]
After some experimentation and looking through the code, it looks like this supports only the `Test` scope.  I like to use the `IntegrationTest` scope to keep my integration tests separated from my unit tests instead of using tags.

Is there a setting that I am missing to enable this?

**Comment by kurtkopchik** [comment]
Hi @Cosmo439,

I have released a new version of the plugin that allows you to change the `Scope` of what is executed by `dockerComposeTest` from the default of `Test` to something else like `IntegrationTest`.

`addSbtPlugin("com.tapad" % "sbt-docker-compose" % "1.0.18")`

1) Update `testCasesPackageTask` to specify IntegrationTest scope
```
testCasesPackageTask := (sbt.Keys.packageBin in IntegrationTest).value
```

2) Update `testCasesJar` to specify IntegrationTest jar
```
testCasesJar := artifactPath.in(IntegrationTest, packageBin).value.getAbsolutePath
```

3) Include any IntegrationTest scoped resources on the classpath if they are used in the tests
```
testDependenciesClasspath := {
  val fullClasspathCompile = (fullClasspath in Compile).value
  val classpathTestManaged = (managedClasspath in IntegrationTest).value
  val classpathTestUnmanaged = (unmanagedClasspath in IntegrationTest).value
  val testResources = (resources in IntegrationTest).value
  (fullClasspathCompile.files ++ classpathTestManaged.files ++ classpathTestUnmanaged.files ++ testResources).map(_.getAbsoluteFile).mkString(":")
}
```

There is also a new example project [basic-with-tests-integration](https://github.com/Tapad/sbt-docker-compose/tree/master/examples/basic-with-tests-integration) showing how to do this.

Thanks for using the plug-in and I hope this provides the `IntegrationTest` scope support that you were looking for.

**Comment by stela** [comment]
Thanks, works for me, allows easy separation of regular unit test cases which can run without external dependencies and integration/acceptance tests requiring docker-compose's containers.
