### ISSUE TITLE
dockerComposeUp broken with Docker 1.13.0

### ISSUE THREAD

**Issue by dpfeiffer** [Tapad/sbt-docker-compose#40]
Today I updated to docker 1.13.0 broke plugin. 

When running `dockerComposeUp` it prints following error:

```
Waiting for container Id to be available for service 'db' time remaining: 499
Error response from daemon: Invalid filter '"name'
```

As you can see there is a `"` before the name, so I guess the error is in `DockerCommands.getDockerContainerId`.

**Comment by kurtkopchik** [comment]
Hi @dpfeiffer, thanks for reporting this issue with the latest 1.13.0 release of Docker. It appears that there was an update to how Docker processes quotes in the `--filter` parameter for the `ps` command.

I have published a `1.0.17-SNAPSHOT` release that should handle this new behavior. Let me know if it works for you and I'll publish an official release.
```
resolvers += "Sonatype Snaopshots" at "https://oss.sonatype.org/content/repositories/snapshots/"
addSbtPlugin("com.tapad" % "sbt-docker-compose" % "1.0.17-SNAPSHOT")
```

Thanks again for using the plugin and providing feedback!

**Comment by dpfeiffer** [comment]
Hi @kurtkopchik, thanks for the fast fix of that issue. It seems to work fine. We really enjoy to use that plugin as it makes life so much easier.

**Comment by kurtkopchik** [comment]
Hi @dpfeiffer, I published an official release with the changes to support Docker v1.13.0.

`addSbtPlugin("com.tapad" % "sbt-docker-compose" % "1.0.17")`

I'm happy to hear that you are finding this plugin to be as useful as we find it to be!
