### ISSUE TITLE
 java.io.FileNotFoundException:../docker-compose.yml (No such file or directory)

### ISSUE THREAD

**Issue by ashishsoni** [Tapad/sbt-docker-compose#45]
I have a multi module project and why do i need to have a docker-compose file in the root directory.
I just want to have the docker-compose file in each subproject and build them from there ...
Not sure why the plugin is looking for the docker-compose file in the root of the multi module prooject

**Comment by kurtkopchik** [comment]
Hi @aashishlalani,

The plugin looks for a docker-compose file for each project that the plugin is enabled for. If you only call `enablePlugins(DockerComposePlugin)` on the sub-projects and not on the root project then you should see the behavior that you are looking for.

For example, if you look at the multi-project example [build.sbt](https://github.com/Tapad/sbt-docker-compose/blob/master/examples/multi-project/build.sbt) file you'll notice that the plugin is enabled on the root as well as the two sub-projects. Removing the root project `enablePlugins(DockerComposePlugin)` [statement](https://github.com/Tapad/sbt-docker-compose/blob/master/examples/multi-project/build.sbt#L7) will leave it just enabled for the two sub-projects.

I hope this solves your issue and thanks for using the plugin!
