### ISSUE TITLE
Tests fail on Docker for Windows

### ISSUE THREAD

**Issue by Tillaert** [Tapad/sbt-docker-compose#48]
- examples/basic-with-test-integration/build.sbt uses linux path separator. (i.e. hardcoded ":" instead of environment dependent path separator)
- exposed ports are not reported on Windows. (Compose file is split using "\r", which does not remove the newlines in windows)
- Test code does not extract correct path format. URL is not properly converted to path.

**Comment by kurtkopchik** [comment]
Thanks again @Tillaert! I've merged your changes and put out a new release with the updates:

`addSbtPlugin("com.tapad" % "sbt-docker-compose" % "1.0.20")`
