### ISSUE TITLE
support multiple docker compose files

### ISSUE THREAD

**Issue by fommil** [Tapad/sbt-docker-compose#66]
maybe I'm missing something in the docs? It would be really useful to be able to have multiple different configurations, e.g. one for integration tests, another for performance tests.

By using a `Command` instead of a `Task` it means we can't have per-project settings. But perhaps names of configs could be used instead? e.g. `dockerComposeUp --config=perf`

**Comment by kurtkopchik** [comment]
Hi @fommil - Have you taken a look at the [basic-with-tests-integration](https://github.com/Tapad/sbt-docker-compose/tree/master/examples/basic-with-tests-integration) example?

**Comment by fommil** [comment]
I have now, thanks. But that's not doing what I'm looking for (I don't think).

Let's say I have a multiple project build, with `core` (which has integration tests) and `performance` which is a performance test benchmark. I have a docker compose file that I want to run before I run my `core/it:test` task and I have a different docker compose file that I want to run for my `performance` benchmarks.

**Comment by kurtkopchik** [comment]
Hi @fommil - To do this you would define a separate `docker-compose.yml` file and set of tests within both the `performance` and `core` projects. The `docker-compose.yml` file in the `performance` project can be defined to reference the image built within the `core` project using the `<localBuild>` tag on the `image:` definition.

I pushed a sample project [multi-project-2](https://github.com/Tapad/sbt-docker-compose/tree/test/multiproject) on a branch to show you how:

- In `build.sbt` a separate `performance` [project](https://github.com/Tapad/sbt-docker-compose/blob/test/multiproject/examples/multi-project-2/build.sbt#L38) created. 

- This project has it's own [docker-compose](https://github.com/Tapad/sbt-docker-compose/blob/test/multiproject/examples/multi-project-2/performance/docker/docker-compose.yml) definition file. You can put whatever you would like in this compose file for your `performance` configuration but I set it to use the same image built by the `core` project. This is done with the `<localBuild>` defined on the image:
`image: core:latest<localBuild>`

- This project also defines it's own set of [performance](https://github.com/Tapad/sbt-docker-compose/blob/test/multiproject/examples/multi-project-2/performance/src/test/scala/PerformanceSpec.scala) test cases that are run against this docker-compose config when `dockerCompseTest` is executed within the scope of this project.

- Executing both the `core` set tests the `performance` suite of tests, each with there own compose file definitions, would look like the following:

```
> projects
[info] 	   core
[info] 	 * multi-project-2
[info] 	   performance
> project core
> dockerComposeTest
Starting Test Pass against a new local Docker Compose instance.
...

CoreSpec:
Map(core:5005 -> localhost:32843, core:8080 -> localhost:32842, core:containerId -> f8d761ede773)
Attempting to connect to: localhost:32842, container id is f8d761ede773
- Core Test: Validate that the Docker Compose endpoint returns a success code and the string 'Hello, World!'
Run completed in 240 milliseconds.
Total number of tests run: 1

...

> project performance
> dockerComposeTest
Starting Test Pass against a new local Docker Compose instance.
...

PerformanceSpec:
Add performance testing code here...
- Peformance Test: Template'
Run completed in 116 milliseconds.
Total number of tests run: 1

...
>
```

**Comment by fommil** [comment]
thanks Kurt, there was no need to do that :smile: once I realised that you *intended* for `Command`s to be used this way it made sense... I think it would be a lot easier to understand if everything was a `Task` instead of a `Command`. Is there any particular reason why you did it this way?
