### ISSUE TITLE
auto cleanup on sbt exit

### ISSUE THREAD

**Issue by fommil** [Tapad/sbt-docker-compose#68]
It would be good to have the option to `stop` all docker instances for all projects on sbt exit.

In addition, there doesn't seem to be a way to do this kind of logic in CI: `... start docker ... try { ... normal integration tests ... } finally { ... stop instance ...}` since `sbt dockerComposeUp it:test dockerComposeStop` will halt at `it:test` if they fail (I think).

**Comment by kurtkopchik** [comment]
The way to do this is to use `dockerComposeTest` to run your integration tests against the docker instance. This is how we run our integration tests on our CI server. `dockerComposeTest` will:
1) Start your compose instance
2) Run your integration tests
3) Stop the docker compose instance regardless if the tests pass or fail

**Comment by fommil** [comment]
right, but that involves running the tests *inside* the container. We are using docker-compose to launch the service and then run our normal sbt tests, talking to that container over a port.

As a workaround, we start `sbt` twice... the second time runs `dockerComposeStop`. That said, I think CI cleans everything up for us anyway. We could be leaking.

**Comment by kurtkopchik** [comment]
Unless I'm missing something in your explanation `dockerComposeTest` does indeed run the test cases outside of a container / the docker compose instance. The docker instance `host` and `port` information for each `service` are supplied to the `configMap` in each test case allowing the integration tests to run externally and communicate to the containers via the their externally exposed host/port info.

Checkout the [basic-with-tests](https://github.com/Tapad/sbt-docker-compose/blob/master/examples/basic-with-tests/src/test/scala/BasicAppSpec.scala#L25) example.

**Comment by fommil** [comment]
hmm, I may have misunderstood what these commands are doing. I'm not really comfortable with a `Command` running my tests though so I may stick with the original workaround.

**Comment by fommil** [comment]
in any case, that usecase was a bit of a digression, the thing I was really thinking of is: it would be good to have an sbt exit hook that shuts down everything.
