### ISSUE TITLE
use native docker, not require docker-machine

### ISSUE THREAD

**Issue by fommil** [Tapad/sbt-docker-compose#71]
I'm running on GNU/Linux and have the luxury of a native docker. But `sbt-docker-compose` insists that I use a `docker-machine` with a name.

This is posing a problem because `sbt-native-packager` is publishing to my native docker, not the `docker-machine` named `default` (same with our CI)

Could there please be an option to use native docker? (A workaround to publish to the docker-machine would be appreciated)

**Comment by kurtkopchik** [comment]
Hi @fommil, the plugin supports:
- Docker Toolbox
- Docker for Mac
- Native Docker on Linux (which we also use on our CI servers)

`docker-machine` should not be required as our CI servers also run native docker.  Can you provide me with the logs and error that you are seeing? Which environment the plugin detects is in the output from `dockerComposeUp`.

We [check](https://github.com/Tapad/sbt-docker-compose/blob/1b7ecfa29fb86e316f8eb92e45248703cfc00b19/src/main/scala/com/tapad/docker/DockerCommands.scala#L80) if `docker-machine` should be used based on the existence of the environment variable `DOCKER_MACHINE_NAME`.  Is that defined on your linux build machines for some reason?
`def isBoot2DockerEnvironment: Boolean = sys.env.get("DOCKER_MACHINE_NAME").isDefined`

**Comment by fommil** [comment]
ok, thanks. This is probably a false route of me trying to investigate #70
