### ISSUE TITLE
Wrong environment detected

### ISSUE THREAD

**Issue by mb720** [Tapad/sbt-docker-compose#74]
This is a cosmetic issue.

After upgrading from version 17 to version 22, the plugin thinks I'm on OSX while I'm on Win 10 x64 using [Git Bash](https://git-for-windows.github.io/) as my command line.

The log message in version 17 is 

> Non-OSX environment detected. Using the host from the container.

On 22 it's

> Docker for Mac environment detected. Using the localhost for the container.

It doesn't bother me and apart from that, everything's fine.

I'm using Docker Version 17.03.1-ce-win12 (12058)

**Comment by kurtkopchik** [comment]
Hi @mb720, thanks for reporting this issue! I've pushed a [change](https://github.com/Tapad/sbt-docker-compose/commit/5b61e0cc506eeeca312e6a598244978c319661f6) that will be included in the next release that will update the environment detection text. As you correctly pointed out it can be either Docker for Mac _or_ Docker for Windows. The text for when a "Docker for" type of environment is detected will now read `Docker for Mac/Windows environment detected. Using the localhost for the container.`

**Comment by kurtkopchik** [comment]
The fix for this issue is now included in an official release:

`addSbtPlugin("com.tapad" % "sbt-docker-compose" % "1.0.23")`

Thanks for the feedback and using the plugin!

**Comment by mb720** [comment]
I just updated and ran it. Looks good to me, thanks! 👍
