### ISSUE TITLE
Tests seemingly executed on host

### ISSUE THREAD

**Issue by mb720** [Tapad/sbt-docker-compose#75]
Hi!

I'm trying to execute [a test](https://gitlab.com/bullbytes/scala-js-example/blob/master/app/jvm/src/test/scala/server/PeopleSpec.scala#L41) that queries the database which runs in its own container.

The database is Postgres and I configure it using environment variables in my [docker-compose.yml](https://gitlab.com/bullbytes/scala-js-example/blob/master/docker-compose.yml#L31).

The test currently fails since I can't connect to the database.

> SEVERE: Connection error:
> org.postgresql.util.PSQLException: The connection attempt failed.
> ...
> Caused by: java.net.UnknownHostException: postgresForScalaJsExample

For debugging, I print out the name and value of each environment variable in the test suite. This should contain the credentials for the database.

When I executed `dockerComposeTest skipPull` I was in for a surprise: I saw the environment variables of my Windows host system.

Is this a bug? I'm not sure anymore where the tests are executed, on the host or inside the Docker VM?

Thanks a lot in advance!

**Comment by kurtkopchik** [comment]
Hi @mb720, the tests are executed on the host machine against the running Docker compose instance. The endpoint host/post mappings for each Docker service are passed to the test cases via the ScalaTest configMap. Check out the basic-with-tests example.

**Comment by mb720** [comment]
Hi Kurt!

Thanks for clearing that up.

I got [my tests](https://gitlab.com/bullbytes/scala-js-example/blob/master/app/jvm/src/test/scala/server/PeopleSpec.scala) running.

This is amazing, thanks! :-)

**Comment by kurtkopchik** [comment]
Happy to hear. I'm glad everything is working now!
