### ISSUE TITLE
Document system properties support

### ISSUE THREAD

**Issue by ches** [Tapad/sbt-docker-compose#79]
I only discovered the feature from #10 when I happened to read a test case for it in the source. It's a high-level feature that is probably worth documenting in the README.

**Comment by kurtkopchik** [comment]
Hi @ches - Thanks for pointing this out! I've updated the README to include information about the system properties support: https://github.com/Tapad/sbt-docker-compose/commit/c791e310bd6c3eabf4f4c358eef199aca3874577
