### ISSUE TITLE
dockerComposeTest classpath differs from SBTs test classpath

### ISSUE THREAD

**Issue by dpfeiffer** [Tapad/sbt-docker-compose#85]
If I have an `application.conf` file in `src/main/resources` and in `src/test/resources/` `dockerComposeTest` picks the one from `src/main/resources/` and SBT test the other one. This might be solved by changing the way the `testDependenciesClasspath` is built. (as mentioned in #36 )

```
testDependenciesClasspath := {
  val fullClasspathCompile = (fullClasspath in Compile).value
  val classpathTestManaged = (managedClasspath in Test).value
  val classpathTestUnmanaged = (unmanagedClasspath in Test).value
  val testResources = (resources in Test).value
  (testResources ++ fullClasspathCompile.files ++ classpathTestManaged.files ++ classpathTestUnmanaged.files).map(_.getAbsoluteFile).mkString(":")
}
```

**Comment by kurtkopchik** [comment]
Hi @dpfeiffer - I've made the change you requested and released the `SNAPSHOT` version below:

```
resolvers += "Sonatype Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots/"
addSbtPlugin("com.tapad" % "sbt-docker-compose" % "1.0.25-SNAPSHOT")
```

Let me know if it works for you and I'll be sure to have it included in the next official release. Thanks for reporting the issue along with a suggested fix!

**Comment by dpfeiffer** [comment]
Hi @kurtkopchik, thanks for the fast response. I tried it out with one of our services and it works well.

**Comment by kurtkopchik** [comment]
Hi @dpfeiffer,

I'm glad to hear that it works! I put out an official release with this update:
`addSbtPlugin("com.tapad" % "sbt-docker-compose" % "1.0.25")`
