### ISSUE TITLE
SBT 1.0.0 support

### ISSUE THREAD

**Issue by mb720** [Tapad/sbt-docker-compose#90]
Hi!

I was trying to use your plugin with SBT 1.0.0 but got this error:

> [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
> [warn] 	::          UNRESOLVED DEPENDENCIES         ::
> [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
> [warn] 	:: com.tapad#sbt-docker-compose;1.0.26: not found
> [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
> [warn] 
> [warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
> [warn] 		com.tapad:sbt-docker-compose:1.0.26 (scalaVersion=2.12, sbtVersion=1.0)
> [warn] 
> [warn] 	Note: Unresolved dependencies path:
> [warn] 		com.tapad:sbt-docker-compose:1.0.26 (scalaVersion=2.12, sbtVersion=1.0) (/home/mb/dev/scala/scala-js-example/project/plugins.sbt#L14-15)

This is in my plugins.sbt: 

    addSbtPlugin("com.tapad" % "sbt-docker-compose" % "1.0.26")

Let me know if I can provide further information.

All the best,
Matthias

**Comment by epishkin** [comment]
https://github.com/Tapad/sbt-docker-compose/pull/89

**Comment by mb720** [comment]
Thanks epishkin, I thought that this merge was already included in the 1.0.26 release.

**Comment by kurtkopchik** [comment]
Hi @mb720,

I just released version `1.0.27 `of the plugin with support for `sbt 1.0.0`. Let me know if it works for you and we can close this issue out.

`addSbtPlugin("com.tapad" % "sbt-docker-compose" % "1.0.27")`

**Comment by mb720** [comment]
Beautiful! `1.0.27` works great with SBT 1.0.0 on Arch Linux 4.12.8. Docker version is `17.06.0-ce`.
