### ISSUE TITLE
Support for custom tag?

### ISSUE THREAD

**Issue by lloydmeta** [Tapad/sbt-docker-compose#91]
Currently this plugin uses `version` to pull in a tag, which works for the most part, but in my current project, I'm using different versioning for the project and the Docker Image that I create. I'm also unable to use `latest`.

If possible I'd like to change this line https://github.com/Tapad/sbt-docker-compose/blob/5e9ec450d823d76c6d37d423b87f704017162ff1/src/main/scala/com/tapad/docker/ComposeFile.scala#L74 to use `DockerComposeKeysLocal.composeServiceTag` instead of just `version`, and have that pull `version` by default, but overridable in client projects.

What do you think?

**Comment by kurtkopchik** [comment]
Hi @lloydmeta - Thanks for reporting this issue. I've made an initial set of changes that allows you to override the default `version` `SettingKey` and provide whatever value that you would like.

https://github.com/Tapad/sbt-docker-compose/compare/feature/versionTagOverride

Just define `composeServiceVersionTask` in your `build.sbt` file to override the default behavior of using the `version` `SettingKey`:

`composeServiceVersionTask := "1.2.3"`

I've released `1.0.28-SNAPSHOT` with these changes. Let me know if it works for you and I can get it incorporated into the next official release.

```
resolvers += "Sonatype Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots/"
addSbtPlugin("com.tapad" % "sbt-docker-compose" % "1.0.28-SNAPSHOT")
```

Thanks for using the plugin!

**Comment by lloydmeta** [comment]
@kurtkopchik Thanks for the quick response. And thanks for this great plugin :)

I gave your snapshot a try and it works fine. Looking forward to the next official release !

**Comment by kurtkopchik** [comment]
Hi @lloydmeta - This change has now been included in an official release:

`addSbtPlugin("com.tapad" % "sbt-docker-compose" % "1.0.28")`

**Comment by lloydmeta** [comment]
Thanks @kurtkopchik :)
