### ISSUE TITLE
Run tests against a specific project configuration?

### ISSUE THREAD

**Issue by carloscaldas** [Tapad/sbt-docker-compose#92]
I could not find this feature. But I'd to run dockerComposeTest specifically for integration tests and don't want to tag all of my tests since they already belongs to a specific sbt configuration. Is that possible?

**Comment by kurtkopchik** [comment]
Hi @carloscaldas,

Checkout Issue https://github.com/Tapad/sbt-docker-compose/issues/38 which includes instructions for how to support the `IntegrationTest` scope or any other scope you want when executing tests via `dockerComposeTest`.

There is also an example project showing how to set this up:
https://github.com/Tapad/sbt-docker-compose/tree/master/examples/basic-with-tests-integration

Thanks for using the plugin and I hope that this answers your question.

**Comment by carloscaldas** [comment]
Thanks @kurtkopchik
