### ISSUE TITLE
Skip printing test class names which are not being run when running specific tags

### ISSUE THREAD

**Issue by shashidesai** [Tapad/sbt-docker-compose#96]
* This is a nice to have feature.

**Setup**:
* I have two tags in my build.sbt - `UnitTestTag` and `FunctionalTestTag`
Example:

**Test Run**:
* So when I run just unit tests - `$ sbt 'dockerComposeTest -tags:UnitTestTag'`

This is what is printed as part of the test run:
```
Test1FunctionalTest:
Unit1Test:
- test1 description
- test2 description
Unit2Test:
- test1 description
- test2 description
Test2FunctionalTest:
```
* `Test1FunctionalTest` and `Test2FunctionalTest` classes are not run (as they are tagged with FunctionalTestTag) but they show up in the list

**Nice to have feature**:
* Even though the functional tests aren't run, they get printed in the list of tests and are shown green. So it would be nice if we could skip printing the tests which are not part of the tag which we are running.

**Comment by kurtkopchik** [comment]
Hi @shashidesai,

So what I believe is happening is that `ScalaTest` needs to load the class the Functional Tests are contained in to find out if there are any tests within it are tagged for execution. `ScalaTest` then prints the class name even when no tests with the proper tags are found.

What you can do is use the `sbt-docker-compose` `testExecutionArgs` setting in `build.sbt` to provide additional [filtering parameters](http://www.scalatest.org/user_guide/using_the_runner) to ScalaTest for which test Suites or packages to load during test execution by `dockerComposeTest`.

`testExecutionArgs := // Additional ScalaTest Runner argument options to pass into the test runner. For example, this can be used for the generation of test reports.`

For example, if all of your Unit Tests spec names have a suffix of `UnitSpec` then the following setting would never load any of the functional tests and therefore you would not see the Functional Test class names printed in the output:
`testExecutionArgs := "-q UnitSpec"` 

Or you could group your Unit tests in a package "com.company.project.tests.unit" and specify that only tests in that package be considered for execution:
`testExecutionArgs := "-m com.company.project.tests.unit"` 

I hope this helps.

**Comment by shashidesai** [comment]
thanks @kurtkopchik , will try that.
