### ISSUE TITLE
Run specs2 tests in multi-project code?

### ISSUE THREAD

**Issue by mthebridge** [Tapad/sbt-docker-compose#98]
Hi there - I'm moving an existing Scala project to run against containerized versions of our app and this plugin looks excellent - but I'm bumping up against a problem running our existing spec2 tests using `dockerComposeTest` because we use multi-project builds.  Specifically I have two subprojects A and B, and a third project C which just contains shared library code for the others.  This means that while A and B have no dependencies they both need C.

So when the `dockerComposeTest` task  spawns off a separate Java process using the specs2 `FilesRunner`, it can't handle the fact that I have some cross-project dependencies - it expects all my tests and the dependent class paths to be under a single directory.

Is there a way around this?  Ideally I'd like to override the "test" task for the dockerCompose tests, but that doesn't seem possible?

**Comment by kurtkopchik** [comment]
Hi @mthebridge, 

While you can't override the entire "test" task for `dockerComposeTest` you can override a number of the parameters that go into building the final command that is executed.

1) For example you can set `testDependenciesClasspath` in build.sbt to define the class paths to be used when you run `dockerComposeTest`:

`testDependenciesClasspath := // The path to all managed and unmanaged Test and Compile dependencies.  This defaults to all managedClasspath and unmanagedClasspath in the Test and fullClasspath in the Compile Scope.`

The [basic-with-tests-integration](https://github.com/Tapad/sbt-docker-compose/blob/master/examples/basic-with-tests-integration/build.sbt#L26) example shows how to override this setting. 

2) You can also define `testExecutionExtraConfigTask` to provide Specs2 [arguments](https://etorreborre.github.io/specs2/guide/SPECS2-2.4.17/org.specs2.guide.Runners.html) to modify the behavior of the `FilesRunner`.

For example:
`testExecutionExtraConfigTask := Map("filesrunner.verbose" -> s"true")`

From the Specs2 help guide it looks like you should be able to use `filesrunner.path` or `filesrunner.basePath` to have Specs2 find all of the tests that you are interested in running:
```
filesrunner.verbose: display information messages about which classes are found and being instantiated to be executed (false by default)
filesrunner.basePath: source directory containing the specifications (src/test/scala by default)
filesrunner.path: glob pattern used to find specification source files (*/.scala by default)
filesrunner.pattern: regular expression for locating specification names inside a source file (.*Spec by default)
```

Let me know if overriding these plugin settings for `testDependenciesClasspath` and `testExecutionExtraConfigTask` lets you accomplish what you are looking to do.

**Comment by mthebridge** [comment]
Thanks for the speedy reply!   I have looked into those options, but couldn't quite make them work - I'll play around a bit more and let you know.

**Comment by mthebridge** [comment]
Well, looks like I just wasn't trying enough yesterday - with a combination of `filesrunner.basepath`, `filesrunner.pattern` and `testDependenciesClasspath` I have managed to get my tests running (they don't pass yet but that's a different problem I can solve!).  Thanks @kurtkopchik for the pointers, happy to close this issue now.

**Comment by kurtkopchik** [comment]
Hi @mthebridge - Great to hear that it's working now and thanks for using the plugin!
